# Generated by Django 4.2.7 on 2026-05-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, default='', max_length=64)),
                ('category', models.CharField(choices=[('MEDICINE', 'Medicine'), ('ASSETS', 'Assets'), ('SUPPLIES', 'Supplies'), ('EQUIPMENT', 'Equipment'), ('LABORATORY', 'Laboratory')], max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='units', max_length=32)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
