# Generated by Django 4.2.7 on 2026-05-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_ward_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_type',
            field=models.CharField(blank=True, choices=[('MALE', 'Male Ward'), ('FEMALE', 'Female Ward'), ('EMERGENCY', 'Emergency Ward'), ('ICU', 'ICU Ward'), ('PEDIATRICS', 'Pediatrics Ward'), ('LABOR', 'Labor Ward')], default='', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_number')},
        ),
        migrations.RemoveField(
            model_name='bed',
            name='created_at',
        ),
    ]
