# Generated by Django 4.2.7 on 2026-05-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_bed_bed_number_alter_ward_ward_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(max_length=64),
        ),
    ]
