# Generated by Django 5.2.4 on 2026-03-10 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triage', '0002_visit_arrival_mode_visit_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='triage.visit')),
            ],
        ),
    ]
