# Generated by Django 4.2.7 on 2026-05-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_billing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='billing_exempt',
            field=models.CharField(choices=[('NONE', 'Standard billing'), ('EMPLOYEE', 'Hospital employee'), ('DEBT', 'Debt (Pay at discharge)'), ('OTHER', 'Other exempt')], default='NONE', max_length=20),
        ),
    ]
