# Generated by Django 4.2.7 on 2026-05-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_billing_exempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
