# Generated by Django 4.2.7 on 2026-05-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('OPD', 'OPD (Outpatient Department)'), ('PED', 'PED (Pediatrics)'), ('OBGYN', 'OB/GYN (Obstetrics and Gynecology)'), ('IM', 'IM / INT MED (Internal Medicine)'), ('ORTHO', 'ORTHO (Orthopedics)'), ('CARD', 'CARD (Cardiology)'), ('DERM', 'DERM (Dermatology)'), ('ENT', 'ENT (Otolaryngology)'), ('OPH', 'OPH / OPHTH (Ophthalmology)')], max_length=20, null=True),
        ),
    ]
