# Generated by Django 4.2.7 on 2026-05-27 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('triage', '0011_alter_triage_doctor_department'),
        ('nurse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_notes', models.TextField(blank=True, default='')),
                ('vitals_snapshot', models.JSONField(blank=True, null=True)),
                ('commit_type', models.CharField(choices=[('NOTES', 'Notes'), ('VITALS', 'Vitals')], max_length=20)),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_seen', models.BooleanField(default=False)),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'NURSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_observations', to='triage.visit')),
            ],
        ),
    ]
