# Generated by Django 5.2.4 on 2026-03-10 08:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_hospital_id'),
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='arrival_mode',
            field=models.CharField(blank=True, choices=[('POLICE', 'Police'), ('EMS', 'EMS'), ('TAXI', 'Taxi'), ('PRIVATE', 'Private')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='arrival_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='patients.patient')),
            ],
        ),
    ]
