# Generated by Django 5.2.4 on 2026-03-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_alter_visit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('WAITING_RECEPTION', 'Waiting Reception'), ('WAITING_DOCTOR', 'Waiting Doctor'), ('IN_CONSULTATION', 'In Consultation'), ('WAITING_LAB_RESULTS', 'Waiting Lab Results'), ('LAB_RESULTS_READY', 'Lab Results Ready'), ('WAITING_PHARMACY', 'Waiting Pharmacy'), ('CONSULTATION_COMPLETED', 'Consultation Completed')], default='WAITING_RECEPTION', max_length=30),
        ),
    ]
