# Generated by Django 5.2.4 on 2026-03-17 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0005_alter_visit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor currently handling this visit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_admitted',
            field=models.BooleanField(default=False, help_text='If True, the patient is admitted to a bed and stays in ongoing care'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('WAITING_RECEPTION', 'Waiting Reception'), ('WAITING_DOCTOR', 'Waiting Doctor'), ('IN_CONSULTATION', 'In Consultation'), ('WAITING_LAB_RESULTS', 'Waiting Lab Results'), ('LAB_RESULTS_READY', 'Lab Results Ready'), ('WAITING_PHARMACY', 'Waiting Pharmacy'), ('CONSULTATION_COMPLETED', 'Consultation Completed'), ('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged')], default='WAITING_RECEPTION', max_length=30),
        ),
    ]
