# Generated by Django 6.0.3 on 2026-04-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0006_visit_doctor_visit_is_admitted_alter_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='triage_patient_name',
            field=models.CharField(blank=True, default='', help_text='Name entered at triage (before formal registration)', max_length=255),
        ),
    ]
