# Generated by Django 4.2.7 on 2026-05-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0008_visit_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='doctor_department',
            field=models.CharField(blank=True, choices=[('OPD', 'OPD (Outpatient Department)'), ('ER', 'ER / ED (Emergency Department)'), ('PED', 'PED (Pediatrics)'), ('OBGYN', 'OB/GYN (Obstetrics and Gynecology)'), ('IM', 'IM / INT MED (Internal Medicine)'), ('SURG', 'SURG (Surgery Department)'), ('ORTHO', 'ORTHO (Orthopedics)'), ('CARD', 'CARD (Cardiology)'), ('DERM', 'DERM (Dermatology)'), ('ENT', 'ENT (Otolaryngology)'), ('OPH', 'OPH / OPHTH (Ophthalmology)')], help_text='Recommended department for the doctor based on consultation', max_length=20, null=True),
        ),
    ]
