# Generated by Django 4.2.7 on 2026-05-27 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0009_triage_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='registration_number',
        ),
    ]
