# Generated by Django 4.2.7 on 2026-05-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0011_alter_triage_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='doctor_department',
            field=models.CharField(blank=True, choices=[('OPD', 'OPD (Outpatient Department)'), ('PED', 'PED (Pediatrics)'), ('OBGYN', 'OB/GYN (Obstetrics and Gynecology)'), ('IM', 'IM / INT MED (Internal Medicine)'), ('ORTHO', 'ORTHO (Orthopedics)'), ('CARD', 'CARD (Cardiology)'), ('DERM', 'DERM (Dermatology)'), ('ENT', 'ENT (Otolaryngology)'), ('OPH', 'OPH / OPHTH (Ophthalmology)'), ('EMERG', 'EMERG (Emergency)')], help_text='Recommended department for the doctor based on consultation', max_length=20, null=True),
        ),
    ]
