# Generated by Django 4.2.7 on 2026-04-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_laborder_result_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='doctor_lab_result_modal_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborder',
            name='doctor_lab_toast_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacy_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DISPENSED', 'Dispensed')], default='PENDING', max_length=20),
        ),
    ]
