# Generated by Django 4.2.7 on 2026-05-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_lab_flags_and_pharmacy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
    ]
