# Generated by Django 4.2.7 on 2026-05-28 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0006_physicalexamination_admission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicalexamination',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='physicalexamination',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
